### ISSUE TITLE
The kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by Amused-Net** [hzzyyy/pymcef#9]
When I try to run PYMCEF in a down market with no assets exhibiting a positive return, both Jupyter Notebook and QtConsole have the kernel die.

I can provide a dataset and code through PM if you're unable to replicate.
 
Very, very rarely (maybe 1:20 or 1:50) this error dumps out instead of the kernel breaking:

OverflowError: map size not valid in python

**Comment by zhangyi-hu** [comment]
I would appreciate your minimum reproducing example.

Thanks

**Comment by Amused-Net** [comment]
I'm having a lot of issues getting it down to a minimum reproducible example. It is erroring out in a number of weird ways. If I cannot reduce it down in the next 45 minutes or so, I'll send you an email with the full data set and full range of code.

The newest thing that's popped up is:

---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-10-596fc50796c8> in <module>()

      4 #for 2016-2017
----> 5 portfolio_added_data = append_suggested_portfolio(all_pct, 180, 0.0000548)

<ipython-input-9-d235d8091e0a> in append_suggested_portfolio(full_data_set, lookback, rfr)
      4     appended_data_set = pd.DataFrame()
      5     for i in range (210, len(full_data_set)-lookback):
----> 6         next_row = data_efficient_portfolios(data_set = full_data_set, start_date = full_data_set.index[i], end_date = full_data_set.index[i+lookback], rfr = rfr)
      7         appended_data_set = appended_data_set.append(next_row)
      8     return appended_data_set

<ipython-input-8-44adc4152854> in data_efficient_portfolios(start_date, end_date, data_set, rfr)
      7     frt = pym.SimpleEFp(training_set = np.transpose(training_set.values),
      8                    validation_set = np.transpose(training_set.values),
----> 9                    asset_names = training_set.columns)
     10 
     11     #get the portfolio weights along the efficient frontier

~\Anaconda3\lib\site-packages\pymcef\simple_plot.py in __init__(self, **kwargs)
    100                      array index will be used as labels.
    101         """
--> 102         SimpleEF.__init__(self, **kwargs)
    103 
    104     def _get_axis_label_for_risk(self):

~\Anaconda3\lib\site-packages\pymcef\simple.py in __init__(self, **kwargs)
    136         max_sharpe_port_index = self.dic.Max_sharpe_index()
    137         max_omega_port_index = self.dic.Max_omega_index()
--> 138         max_sharpe_port = _get_portfolio(self.dic.Max_sharpe_portfolio())
    139         max_omega_port = _get_portfolio(self.dic.Max_omega_portfolio())
    140         self.critical_port_in_sample = {}

~\Anaconda3\lib\site-packages\pymcef\simple.py in _get_portfolio(port)
     12 def _get_portfolio(port):
     13     prt = {}
---> 14     prt['weight'] = port.Weights().asdict()
     15     prt['risk'] = port.Risk()
     16     prt['reward'] = port.Reward()

~\Anaconda3\lib\site-packages\pymcef\ppslp.py in asdict(self)
    223 
    224     def asdict(self):
--> 225         return _ppslp.map_int_double_asdict(self)
    226 
    227     def __init__(self, *args):

OverflowError: map size not valid in python

**Comment by zhangyi-hu** [comment]
OK, this particular exception doesn't seem hard.

**Comment by Amused-Net** [comment]
This issue was solved with an updated package version emailed to me by hzzyy.
